type EventSentiment = 'negative' | 'neutral' | 'positive';

interface Event {
  text: string;
  sentiment: EventSentiment;
}

const events: Event[] = [
  { text: "Accidentally triggered a death flag. Narrator is concerned.", sentiment: 'negative' },
  { text: "Found a mysterious glowing object. Probably not important.", sentiment: 'neutral' },
  { text: "Met a talking cat. Didn't sign the contract.", sentiment: 'positive' },
  { text: "Discovered a hidden hot spring. Fan service increased.", sentiment: 'positive' },
  { text: "Triggered a random encounter. It's actually just a merchant.", sentiment: 'neutral' },
  { text: "Entered a tournament arc. Will take several episodes.", sentiment: 'neutral' },
  { text: "Met a tsundere. They definitely don't like you. B-baka!", sentiment: 'negative' },
  { text: "Found a convenient plot device. Will use later.", sentiment: 'positive' },
  { text: "Stepped on a landmine. Not the explosive kind.", sentiment: 'negative' },
  { text: "Witnessed a training montage. Muscles increased temporarily.", sentiment: 'positive' },
  { text: "Received a letter from the Demon Lord. It's just spam.", sentiment: 'neutral' },
  { text: "Accidentally became a hero. Again.", sentiment: 'neutral' },
  { text: "Found a legendary sword in a stone. It was just decoration.", sentiment: 'negative' },
  { text: "Met the final boss in a coffee shop. Awkward small talk ensued.", sentiment: 'neutral' },
  { text: "Discovered a secret dungeon. It's actually a Starbucks.", sentiment: 'neutral' },
  { text: "Triggered a beach episode. Plot progression halted.", sentiment: 'neutral' },
  { text: "Found a save point. The universe is self-aware.", sentiment: 'positive' },
  { text: "Met a mysterious cloaked figure. It was just a really short guy.", sentiment: 'neutral' },
  { text: "Discovered the power of friendship. +0 to all stats.", sentiment: 'neutral' },
  { text: "Entered a trap. Gender unchanged, disappointingly.", sentiment: 'negative' },
  { text: "Found a gacha machine. Wallet started crying.", sentiment: 'negative' },
  { text: "Met Truck-kun. Survived somehow.", sentiment: 'positive' },
  { text: "Discovered a plot hole. Ignored it professionally.", sentiment: 'neutral' },
  { text: "Triggered a flashback sequence. Lost 5 minutes.", sentiment: 'negative' },
  { text: "Found the chosen one. It wasn't you.", sentiment: 'negative' },
  { text: "Discovered a hidden boss. Noped out immediately.", sentiment: 'negative' },
  { text: "Met a childhood friend. Lost the main girl position.", sentiment: 'negative' },
  { text: "Found a mysterious egg. Not touching that.", sentiment: 'neutral' },
  { text: "Triggered a cooking mini-game. Burned water.", sentiment: 'negative' },
  { text: "Met a loli. FBI open up!", sentiment: 'negative' },
  { text: "Discovered power levels. They're over 9000!", sentiment: 'positive' },
  { text: "Found a transformation sequence. Takes 3 episodes.", sentiment: 'neutral' },
  { text: "Met a rival. They have cooler hair.", sentiment: 'negative' },
  { text: "Discovered a harem route. Confusion intensified.", sentiment: 'neutral' },
  { text: "Found a cheat skill. It's farming.", sentiment: 'neutral' },
  { text: "Met a goddess. She's useless.", sentiment: 'negative' },
  { text: "Discovered a dungeon. It's full of slimes.", sentiment: 'neutral' },
  { text: "Found a rare drop. It's vendor trash.", sentiment: 'negative' },
  { text: "Met a generic elf. She likes forests.", sentiment: 'neutral' },
  { text: "Discovered a dragon. It wants to be your waifu.", sentiment: 'positive' },
  { text: "Found a magic academy. Everyone is OP except you.", sentiment: 'negative' },
  { text: "Met a vampire. Sparkles disappointingly absent.", sentiment: 'neutral' },
  { text: "Discovered a ninja village. Everyone saw you coming.", sentiment: 'negative' },
  { text: "Found a mecha. No instruction manual included.", sentiment: 'neutral' },
  { text: "Met a zombie. It wants brains. Yours are safe.", sentiment: 'neutral' },
  { text: "Discovered a time loop. Déjà vu intensifies.", sentiment: 'neutral' },
  { text: "Found a guild. Registration paperwork is endless.", sentiment: 'negative' },
  { text: "Met a deity. They're into mobile games.", sentiment: 'neutral' },
  { text: "Discovered a prophecy. You're not in it.", sentiment: 'negative' },
  { text: "Found a legendary treasure. It's a cabbage.", sentiment: 'negative' },
  // Dark fantasy events
  { text: "Found a pile of teeth arranged in a perfect circle. Left it alone.", sentiment: 'negative' },
  { text: "The wind carries whispers of a name you've never heard but somehow know.", sentiment: 'neutral' },
  { text: "Passed a gibbet at the crossroads. The occupant waved.", sentiment: 'negative' },
  { text: "Discovered a well filled entirely with black feathers. Drank from it anyway.", sentiment: 'negative' },
  { text: "A stranger offered directions. Their mouth didn't move when they spoke.", sentiment: 'negative' },
  { text: "Found an abandoned camp. The fire was still warm. The food was still chewing.", sentiment: 'negative' },
  { text: "The local graveyard has more exits than entrances.", sentiment: 'neutral' },
  { text: "A raven landed on your shoulder and recited your sins. It missed a few.", sentiment: 'neutral' },
  { text: "Stumbled upon a shrine to a god with no name. Left an offering of anxiety.", sentiment: 'neutral' },
  { text: "The trees here grow in shapes that look like screaming. Probably a coincidence.", sentiment: 'negative' },
  { text: "Found a sword driven into a skull. The skull asked you to pull it out.", sentiment: 'neutral' },
  { text: "A funeral procession passed. They were burying someone who looked exactly like you.", sentiment: 'negative' },
  { text: "Discovered a village where everyone smiles. They haven't stopped for three years.", sentiment: 'negative' },
  { text: "The moon had a face tonight. It looked disappointed.", sentiment: 'neutral' },
  { text: "Passed through a battlefield. Some of the dead were still arguing.", sentiment: 'neutral' },
  { text: "A plague doctor offered a free checkup. Their medicine bag was full of centipedes.", sentiment: 'negative' },
  { text: "Found a door standing alone in an empty field. Knocked. Something knocked back.", sentiment: 'negative' },
  { text: "The innkeeper served a meal that tasted like regret and copper. Five stars.", sentiment: 'neutral' },
  { text: "Saw your reflection blink independently. Decided mirrors are overrated.", sentiment: 'negative' },
  { text: "A child offered you a flower. It was made of dried blood. Still pretty, though.", sentiment: 'neutral' },
  { text: "The road behind you no longer exists. The road ahead smells like iron.", sentiment: 'negative' },
  { text: "Found a library where the books read you. Left a terrible review.", sentiment: 'neutral' },
  { text: "A merchant sold you 'bottled last words.' They're surprisingly affordable.", sentiment: 'neutral' },
  { text: "The bells of a distant cathedral ring. There is no cathedral in that direction.", sentiment: 'negative' },
  { text: "Helped an old woman cross a bridge. She weighed nothing. Cast no shadow.", sentiment: 'neutral' },
  { text: "Woke up with an extra scar. No memory of earning it. It spells a word.", sentiment: 'negative' },
  { text: "A wolf watched you from the treeline. It was standing upright. Wearing boots.", sentiment: 'neutral' },
  { text: "Found a wanted poster with your face. The crime listed is 'existing.'", sentiment: 'negative' },
  { text: "The sunset was beautiful. Then you realized suns don't set in the north.", sentiment: 'negative' },
  { text: "Drank from a stream. Gained a memory that isn't yours. It's a good one, at least.", sentiment: 'positive' },
  // Spicy / innuendo events (Crush Crush flavor)
  { text: "The barmaid asked if you wanted it 'long, hard, and on the rocks.' She meant the ale. Probably.", sentiment: 'positive' },
  { text: "A succubus complimented your stamina stat. Blushed for three encounters straight.", sentiment: 'positive' },
  { text: "The healer offered a 'full-body inspection.' She was very thorough.", sentiment: 'positive' },
  { text: "Got a hobby unlocked: 'Polishing the Princess's Tiara.' It's not a metaphor. Mostly.", sentiment: 'positive' },
  { text: "The dragon waifu purred and called you 'tiny adventurer.' Your ego: -3. Your everything else: +5.", sentiment: 'neutral' },
  { text: "Tripped, fell, and somehow ended up in the elf queen's bath. Classic protagonist landing.", sentiment: 'positive' },
  { text: "The blacksmith's daughter offered to 'work your shaft.' She meant the spear. You hope.", sentiment: 'neutral' },
  { text: "Your tsundere companion left rations on your bedroll. With a love note. With teeth marks.", sentiment: 'positive' },
  { text: "Accidentally walked in on the party's hot spring scene. Lost 5 sanity, gained 5 affection.", sentiment: 'positive' },
  { text: "A nun whispered her confession. You're not allowed to repeat it but the diary self-censored.", sentiment: 'neutral' },
  { text: "The mage offered to 'cast a spell on you.' She winked. The spell was definitely not in the books.", sentiment: 'positive' },
  { text: "Your familiar got jealous when the catgirl sat on your lap. Now there are two on your lap.", sentiment: 'positive' },
  { text: "The vampire countess bit your neck. Then your ear. Then asked if you were 'free Friday.'", sentiment: 'positive' },
  { text: "Bought a cursed pendant. Side effect: every NPC of the preferred gender now winks at you.", sentiment: 'positive' },
  { text: "Slime girl tried to 'absorb' you. The party intervened. You almost asked them not to.", sentiment: 'neutral' },
  { text: "The merchant offered a discount for a kiss. You haggled her up to two.", sentiment: 'positive' },
  { text: "Won a swimsuit contest you didn't enter. The trophy is a phone number.", sentiment: 'positive' },
  { text: "The demon lord's daughter slipped you her tower address. 'Bring snacks.' Underlined twice.", sentiment: 'positive' },
  { text: "Slept at the inn. Woke up with three companions in the bed and zero memory of how.", sentiment: 'neutral' },
  { text: "The oracle foretold your destiny: 'Many lovers. Some survive.'", sentiment: 'neutral' }
];

export type { Event };

export const generateEventLog = (): Event => {
  return events[Math.floor(Math.random() * events.length)];
};
