const events = [
  "Accidentally triggered a death flag. Narrator is concerned.",
  "Found a mysterious glowing object. Probably not important.",
  "Met a talking cat. Didn't sign the contract.",
  "Discovered a hidden hot spring. Fan service increased.",
  "Triggered a random encounter. It's actually just a merchant.",
  "Entered a tournament arc. Will take several episodes.",
  "Met a tsundere. They definitely don't like you. B-baka!",
  "Found a convenient plot device. Will use later.",
  "Stepped on a landmine. Not the explosive kind.",
  "Witnessed a training montage. Muscles increased temporarily.",
  "Received a letter from the Demon Lord. It's just spam.",
  "Accidentally became a hero. Again.",
  "Found a legendary sword in a stone. It was just decoration.",
  "Met the final boss in a coffee shop. Awkward small talk ensued.",
  "Discovered a secret dungeon. It's actually a Starbucks.",
  "Triggered a beach episode. Plot progression halted.",
  "Found a save point. The universe is self-aware.",
  "Met a mysterious cloaked figure. It was just a really short guy.",
  "Discovered the power of friendship. +0 to all stats.",
  "Entered a trap. Gender unchanged, disappointingly.",
  "Found a gacha machine. Wallet started crying.",
  "Met Truck-kun. Survived somehow.",
  "Discovered a plot hole. Ignored it professionally.",
  "Triggered a flashback sequence. Lost 5 minutes.",
  "Found the chosen one. It wasn't you.",
  "Discovered a hidden boss. Noped out immediately.",
  "Met a childhood friend. Lost the main girl position.",
  "Found a mysterious egg. Not touching that.",
  "Triggered a cooking mini-game. Burned water.",
  "Met a loli. FBI open up!",
  "Discovered power levels. They're over 9000!",
  "Found a transformation sequence. Takes 3 episodes.",
  "Met a rival. They have cooler hair.",
  "Discovered a harem route. Confusion intensified.",
  "Found a cheat skill. It's farming.",
  "Met a goddess. She's useless.",
  "Discovered a dungeon. It's full of slimes.",
  "Found a rare drop. It's vendor trash.",
  "Met a generic elf. She likes forests.",
  "Discovered a dragon. It wants to be your waifu.",
  "Found a magic academy. Everyone is OP except you.",
  "Met a vampire. Sparkles disappointingly absent.",
  "Discovered a ninja village. Everyone saw you coming.",
  "Found a mecha. No instruction manual included.",
  "Met a zombie. It wants brains. Yours are safe.",
  "Discovered a time loop. Déjà vu intensifies.",
  "Found a guild. Registration paperwork is endless.",
  "Met a deity. They're into mobile games.",
  "Discovered a prophecy. You're not in it.",
  "Found a legendary treasure. It's a cabbage."
];

export const generateEventLog = (): string => {
  return events[Math.floor(Math.random() * events.length)];
};
